### ISSUE TITLE
Add tests to examine CST before visitor

### ISSUE THREAD

**Issue by mattbishop** [mattbishop/sql-jsonpath-js#19]
Right now the unit tests examine the visitor output. Those tests are good, but I want to add CST tests to validate the parsed syntax before it is visited.

@JeffML I found a full BNF for SQL JSON Path and checked it in, so this new test suite will help validate it is being followed correctly.

**Comment by JeffML** [comment]
Ok.

**Comment by mattbishop** [comment]
Resolved in #20
